
CREATE TABLE `AN002_RUOLO` (
  `AN002_ID` int NOT NULL AUTO_INCREMENT,
  `AN002_DESCRIZIONE` varchar(200) NOT NULL,
  `AN002_COD_RUOLO` varchar(200) NOT NULL,
  `AN002_DATA_CREAZIONE` datetime(6) NOT NULL DEFAULT NOW(6),
  `AN002_COD_UTENTE_CREAZIONE` varchar(50) NOT NULL,
  `AN002_STATO` varchar(1) NOT NULL DEFAULT 'E',
  `AN002_DATA_MODIFICA` datetime(6) DEFAULT NULL,
  `AN002_COD_UTENTE_MODIFICA` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`AN002_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE AN002_RUOLO AUTO_INCREMENT = 1;