INSERT INTO AN002_RUOLO (
	 AN002_DESCRIZIONE,
     AN002_COD_RUOLO,
     AN002_COD_UTENTE_CREAZIONE
)
VALUES (
	'CREATE, INSERT, UPDATE, DELETE, READ',
    'ADMIN',
    'PA'
);

INSERT INTO AN002_RUOLO (
	 AN002_DESCRIZIONE,
     AN002_COD_RUOLO,
     AN002_COD_UTENTE_CREAZIONE
)
VALUES (
	'INSERT, UPDATE, READ',
    'SIMPLE_USER',
    'PA'
);